### ISSUE TITLE
rolling: true

### ISSUE THREAD

**Issue by szarouski** [TencentRdmCi/session-memory-store#2]
Hi, I can't figure out a way to make this store to work with `rolling: true` which is supposed to update expiration time based on user activity. `rolling: true` works well with built-in MemoryStore, but not with this store. If this is not something that is currently supported, please consider this issue as a feature request.

Thank you.

**Comment by roccomuso** [comment]
Try this one: [memorystore](/roccomuso/memorystore)

**Comment by szarouski** [comment]
Thank you. I didn't try this out as I don't need it ATM, but hopefully this will be useful in future.
