### ISSUE TITLE
Security vulnerability: Depends on an insecure version of lodash

### ISSUE THREAD

**Issue by Dill1** [TencentRdmCi/session-memory-store#5]
The latest version is identified by npm audit as a security vulnerability because it depends on an insecure version of lodash:
https://nodesecurity.io/advisories/577

**Comment by eviltik** [comment]
@xiaoyuze88 please ! :D

**Comment by xiaoyuze88** [comment]
close #6

**Comment by eviltik** [comment]
thanks a lot
